# Generated by Django 5.1.3 on 2024-11-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='desc',
        ),
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.ImageField(default='/static/assets/images/course/1.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='course',
            name='img1',
            field=models.ImageField(default='/static/assets/images/team/2.jpg', upload_to='img1/'),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='Calvin Carlo', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='lessons',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.IntegerField(default=49),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='Become a Professional Graphic Designer', max_length=255),
        ),
    ]
