# Generated by Django 5.1.3 on 2024-11-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_description_course_desc_course_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('blog_name', models.CharField(max_length=255)),
                ('blog_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(upload_to='course_images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='img1',
            field=models.ImageField(upload_to='images1/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lessons',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
