# Generated by Django 5.1.3 on 2024-11-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_blog_alter_course_id_alter_course_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_img',
        ),
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default='', upload_to='blog_images/'),
            preserve_default=False,
        ),
    ]
