# Generated by Django 5.0.6 on 2026-01-29 00:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(help_text='Category name (e.g., Degree, Developer)', max_length=100)),
                ('content', models.TextField(blank=True)),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('img', models.ImageField(upload_to='blog_images/')),
                ('read_time_minutes', models.PositiveIntegerField(default=5)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='courses.instructor')),
            ],
            options={
                'ordering': ['-publish_date', 'order'],
            },
        ),
    ]
